spring:
  # Basic Config
  application:
    name: typing

  profiles:
    default: local

  # JPA Config
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Logging config
logging:
  level:
    root: INFO

# prometheus & actuator
management:
  endpoints:
    shutdown:
      enabled: false
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: typing-api
    distribution:
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  # Session Config
  servlet:
    session:
      timeout: 60m
  # Tomcat Metric Setting
  tomcat:
    mbeanregistry:
      enabled: true
