spring:
  profiles:
    default: local

---
spring:
  # Profile Config
  config:
    activate:
      on-profile: local
  # Basic Config
  application:
    name: typing

  # MySQL Config
  datasource:
    url: ${DB_URL}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  # JPA Config
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

---
spring:
  # Profile Config
  config:
    activate:
      on-profile: test

  # DB Config
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: ${TEST_DB_DRIVER_CLASS_NAME}

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE