spring:
  profiles:
    default: local

---
spring:
  # Profile Config
  config:
    activate:
      on-profile: local
  # Basic Config
  application:
    name: typing

  # MySQL Config
  datasource:
    url: ${DB_URL}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  # JPA Config
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET_KEY}

  data:
    redis:
      host: localhost
      port: 6379

  # Spring Security OAuth2, Client
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            jwk-set-uri: ${OIDC_JWK_SET_URI}
            user-name-attribute: sub
        registration:
          kakao:
            authorization-grant-type: ${GRANT_TYPE}
            redirect-uri: ${LOGIN_REDIRECT_URI}
            client-name: Kakao
            client-authentication-method: client_secret_post
            client-id: ${REST_API_KEY}
            client-secret: ${CLIENT_SECRET_KEY}
            scope:
              - openid              # OIDC
              - name                # 이름
              - profile_nickname    # 닉네임
              - account_email       # 카카오계정(이메일)

  jackson:
    property-naming-strategy: SNAKE_CASE

---
spring:
  # Profile Config
  config:
    activate:
      on-profile: test

  # DB Config
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: ${TEST_DB_DRIVER_CLASS_NAME}

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: ${JWT_SECRET_KEY}

  # Spring Security OAuth2, Client
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            jwk-set-uri: ${OIDC_JWK_SET_URI}
            user-name-attribute: sub
        registration:
          kakao:
            authorization-grant-type: ${GRANT_TYPE}
            redirect-uri: ${LOGIN_REDIRECT_URI}
            client-name: Kakao
            client-authentication-method: client_secret_post
            client-id: ${REST_API_KEY}
            client-secret: ${CLIENT_SECRET_KEY}
            scope:
              - name                # 이름
              - profile_nickname    # 닉네임
              - account_email       # 카카오계정(이메일)
              - openid              # OIDC

  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE